src/DPE.LabChem.Web/Controllers/Account/UserAdminController.cs
using DPE.LabChem.Domain.Entities;
using DPE.LabChem.Identity.Configuration;
using DPE.LabChem.Identity.Context;
using DPE.LabChem.Identity.Users;
using DPE.LabChem.Infra.Data.ORM.EF;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DPE.LabChem.Web.Controllers.Account
{
	public class UserAdminController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationDbContext _dbContext;
		private LabChemDbContext db = new LabChemDbContext();

		public UserAdminController()
		{

		}

		public UserAdminController(ApplicationUserManager userManager)
		{
            this.UserManager = userManager;
		}

        public ApplicationUserManager UserManager
		{
			get
			{
				return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
			}
			set
			{
				_userManager = value;
			}
		}
        // GET: UserAdmin
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

		#region Register
		public ActionResult Create(int? id)
		{
			if (id == null)
			{
				return View("Register", "_Layout");
			}
			else
			{
				Mural mural = db.Mural.Find(id);

				if (mural == null)
				{
					return HttpNotFound();
				}

				RegisterViewModel registerViewModel = new RegisterViewModel
				{
					UserName = mural.Email,
					FullName = mural.User,
					Email = mural.Email
				};

				return View("Register", "_Layout", registerViewModel);
			}
			
			//return RedirectToAction("Register", "UserAdmin", registerViewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(RegisterViewModel register)
		{
			if (ModelState.IsValid)
			{
				var user = new ApplicationUser
				{
					UserName = register.UserName,
					FullName = register.FullName,
					Email = register.Email,
					DateOfBirth = register.DateOfBirth,
					Skype = register.Skype,
					Bio = register.Bio
				};

				var result = UserManager.Create(user, register.Password);

				if (result.Succeeded)
				{
					return RedirectToAction("Index", "UserAdmin");
				}
				else
				{
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError("", error);
					}									}
			}
			return View("Register", "_Layout");
		}
		#endregion

		// POST: UserAdmin/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete(int id)
		{
			if (ModelState.IsValid)
			{
				if (id == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}

				var user = await UserManager.FindByIdAsync(id.ToString());
				if (user == null)
				{
					return HttpNotFound();
				}
				var result = await UserManager.DeleteAsync(user);
				if (!result.Succeeded)
				{
					ModelState.AddModelError("", result.Errors.First());
					return View();
				}
				return RedirectToAction("Index", "UserAdmin");
			}
			return View();
		}

	}
}

src/DPE.LabChem.Web/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DPE.LabChem.Domain.Entities;
using DPE.LabChem.Infra.Data.ORM.EF;

namespace DPE.LabChem.Web.Controllers
{
    public class CountryController : Controller
    {
        private LabChemDbContext db = new LabChemDbContext();

        // GET: Country
        public async Task<ActionResult> Index()
        {
            return View(await db.Country.ToListAsync());
        }

        // GET: Country/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)  
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = await db.Country.FindAsync(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return PartialView(country);
        }
        public ActionResult Cancel()
		{
			return RedirectToAction("Index");
		}

        // GET: Country/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Country/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Initials,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Country.Add(country);
                await db.SaveChangesAsync();
                return Json(new { success = true, message = "Country created successfully" }, JsonRequestBehavior.AllowGet);
            }
            else 
            {
                //IEnumerable<ModelError> errors = ModelState.Values.SelectMany(items => items.Errors).;

                //var errors = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();

                var errors = string.Join("<br>", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));   // html break instead of " | "

                return Json(new { success = false, message = errors }, JsonRequestBehavior.AllowGet);
            }            
        }

        // GET: Country/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = await db.Country.FindAsync(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return PartialView(country);
        }

        // POST: Country/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Initials,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return Json(new { success = true, message = "Country updated successfully" }, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Index");
            }
            else
            {
                //IEnumerable<ModelError> errors = ModelState.Values.SelectMany(items => items.Errors).;

                //var errors = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();

                var errors = string.Join("<br>", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));   // html break instead of " | "

                return Json(new { success = false, message = errors }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Country/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = await db.Country.FindAsync(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return PartialView(country);
        }

        // POST: Country/DeleteCountry
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<ActionResult> DeleteCountry(int id)
        {
            if (ModelState.IsValid)
            {
                Country country = await db.Country.FindAsync(id);
                db.Country.Remove(country);
                await db.SaveChangesAsync();
                return Json(new { success = true, message = "Country deleted successfully" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //IEnumerable<ModelError> errors = ModelState.Values.SelectMany(items => items.Errors).;

                var errors = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();

                return Json(new { success = false, message = errors }, JsonRequestBehavior.AllowGet);
            }
        }

        // POST: Country/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (ModelState.IsValid)
			{
                Country country = await db.Country.FindAsync(id);
                db.Country.Remove(country);
                await db.SaveChangesAsync();
                return Json(new { success = true, message = "Country deleted successfully" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //IEnumerable<ModelError> errors = ModelState.Values.SelectMany(items => items.Errors).;

                var errors = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();

                return Json(new { success = false, message = errors }, JsonRequestBehavior.AllowGet);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }        
    }
}

src/DPE.LabChem.Web/Views/UserAdmin/Index.cshtml
@model IEnumerable<DPE.LabChem.Identity.Users.ApplicationUser>


@{
	ViewBag.Title += "User Admin";
}

<p>
	<a href="@Url.Action("Create")" class="btn btn-success" data-action="Create">
		<span class="glyphicon glyphicon-plus"></span>
		Create New
	</a>
</p>


<div class="modal fade" id="UserModal" role="dialog">
	<div class="modal-dialog">
		<div id="mainContent" class="modal-content col-sm-12">
		</div>
	</div>
</div>

<div class="col-md-12 col-sm-12 ">
	<div class="x_panel">
		<div class="x_title">
			<h2>Users</h2>
			<ul class="nav navbar-right panel_toolbox">
				<li>
					<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
			<div class="row">
				<div class="col-sm-12">
					<div class="card-box table-responsive">
						<table id="datatable" class="table table-striped table-bordered" style="width:100%">
							<thead>
								<tr>
									<th>User Name</th>
									<th>Full Name</th>
									<th>Email</th>
									<th class="text-right">Action</th>
								</tr>
							</thead>


							<tbody>
								@foreach (var item in Model)
								{
									<tr>
										<td>
											@Html.DisplayFor(modelItem => item.UserName)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.FullName)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Email)
										</td>
										<td align="right">
											<a href="javascript:void(0);" class="glyphicon glyphicon-list green detailUserModal" data-id="@item.Id" title="Details"></a>&nbsp;
											@*@Html.ActionLink(" ", "Details", "Country", new { id = item.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-list green detailCountryModal ", title = "Detail", @data_toggle = "modal", @data_target = "detailCountryModal" })&nbsp;*@
											@Html.ActionLink(" ", "Edit", "UserAdmin", new { id = item.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-edit blue", title = "Edit" })&nbsp;
											@Html.ActionLink(" ", "Delete", "UserAdmin", new { id = item.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-trash red", title = "Delete" })
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@section scripts{
	<script type="text/javascript">
		//$(function () {
		//	$('.detailCountryModal').click(function (e) {
		//		e.preventDefault();
		//		//replace the get with this.href to load the edit page
		//		//$.get('https://developer.mozilla.org/en-US/docs/Web', function (data) {
		//		//	//replace the content returned
		//		//	$("#mainContent").html(data);
		//		//});
		//		//show the modal
		//		$('#countryModal').modal({
		//			keyboard: true,
		//		}, 'show');
		//		return false;
		//	})
		//})

		var TeamDetailPostBackURL = '/UserAdmin/Details';
		$(function () {
			$(".detailUserModal").click(function () {
				debugger;
				var $buttonClicked = $(this);
				var id = $buttonClicked.attr('data-id');
				var options = { keyboard: true };
				$.ajax({
					type: "GET",
					url: TeamDetailPostBackURL,
					contentType: "application/json; charset=utf-8",
					data: { "Id": id },
					datatype: "json",
					success: function (data) {
						debugger;
						$('#mainContent').html(data);
						$('#countryModal').modal(options);
						$('#countryModal').modal('show');

					},
					error: function () {
						alert("Dynamic content load failed.");
					}
				});
			});
			//$("#closebtn").on('click',function(){
			//    $('#myModal').modal('hide');

			//$("#closbtn").click(function () {
			//	$('#myModal').modal('hide');
			//});
		});
	</script>
}

src/DPE.LabChem.Web/Views/UserAdmin/Register.cshtml
@model DPE.LabChem.Identity.Users.RegisterViewModel

@{
    ViewBag.Title = "Register";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()	

	<div class="page-title">
		<div class="title_left">
			<h3>User</h3>
		</div>
	</div>
	<div class="clearfix"></div>
	<div class="row">
		<div class="col-md-12 col-sm-12 ">
			<div class="x_panel">
				<div class="x_title">
					<h2>Register User</h2>
					<ul class="nav navbar-right panel_toolbox">
						<li>
							<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</li>
						<li>
							<a class="close-link"><i class="fa fa-close"></i></a>
						</li>
					</ul>
					<div class="clearfix"></div>
					
				</div>
				<div class="x_content">
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })

					<br />					
					<form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
						<div class="item form-group">
							<label class="col-form-label col-md-3 col-sm-3 label-align">
								User Name <span class="required">*</span>
							</label>
							<div class="col-md-4 col-sm-6 ">
								@Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })								
							</div>
						</div>
						<div class="item form-group">
							<label class="col-form-label col-md-3 col-sm-3 label-align">
								Full Name <span class="required">*</span>
							</label>
							<div class="col-md-4 col-sm-6 ">
								@Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
							</div>
						</div>
						<div class="item form-group">
							<label class="col-form-label col-md-3 col-sm-3 label-align">
								Date Of Birth <span class="required">*</span>
							</label>
							<div class="col-md-4 col-sm-6 ">
								@Html.EditorFor(model => model.DateOfBirth, 
										new { htmlAttributes = new  {
											@class = "date-picker form-control",
											@placeholder = "dd-mm-yyyy",
											@type = "text",
											@onfocus = "this.type='date'",
											@onmouseover = "this.type='date'",
											@onclick = "this.type='date'",
											@onblur = "this.type='text'",
											@onmouseout = "timeFunctionLong(this)"
										} })
								<script>
									function timeFunctionLong(input) {
										setTimeout(function() {
											input.type = 'text';
										}, 60000);
									}
								</script>
								@Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
							</div>
						</div>

						<div class="item form-group">
							<label class="col-form-label col-md-3 col-sm-3 label-align">
								Skype 
							</label>
							<div class="col-md-4 col-sm-6 ">
								@Html.EditorFor(model => model.Skype, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.Skype, "", new { @class = "text-danger" })
							</div>
						</div>						
						<div class="item form-group">
							<label class="col-form-label col-md-3 col-sm-3 label-align">
								Bio 
							</label>
							<div class="col-md-4 col-sm-6 ">
								@Html.TextAreaFor(model => model.Bio, new { @class = "form-control" })
								@Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
							</div> 
						</div>
						<div class="item form-group">
							<label class="col-form-label col-md-3 col-sm-3 label-align">
								Email <span class="required">*</span>
							</label>
							<div class="col-md-4 col-sm-6 ">
								@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
							</div>
						</div>
						<div class="item form-group">
							<label class="col-form-label col-md-3 col-sm-3 label-align">
								Password <span class="required">*</span>
							</label>
							<div class="col-md-4 col-sm-6 ">
								@Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
							</div>
						</div>						
						<div class="item form-group">
							<label class="col-form-label col-md-3 col-sm-3 label-align">
								Confirm Password
							</label>
							<div class="col-md-4 col-sm-6 ">
								@Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
							</div>
						</div>
						<div class="ln_solid"></div>

						<div class="item form-group">
							<div class="col-md-6 col-sm-6 offset-md-3">
								<input type="button" value="Cancel" class="btn btn-primary" />
								<input type="submit" value="Submit" class="btn btn-success" />
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>    
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}